project_name: bytedance
target_url: "https://jobs.bytedance.com/experienced/position"
max_pages: 100
headless: true
crawler:
  patterns:
    next_button:
      - "li[title='下一页']"
interceptors:
  - "disable_trace"
page_actions:
  - type: "hover"
    selector: "li[title='下一页']"
after_response:
  - type: "save_json"
    url_contains: "api/v1/search/job/posts"
rate_limit:
  requests_per_minute: 35
  burst_capacity: 3
  min_interval: 1.2
