project_name: dji
target_url: "https://we.dji.com/zh-CN/social?page=1&from=home_page"
max_pages: 100
headless: true
crawler:
  patterns:
    next_button:
      - "li[title='下一页']"
page_actions:
  - type: "save_html"
    clean_html: true
