project_name: game163
target_url: "https://hr.game.163.com/recruit.html"
max_pages: 100
headless: false
page_actions:
  - type: "save_html"
    clean_html: true
rate_limit:
  requests_per_minute: 35
  burst_capacity: 3
  min_interval: 1.2
