project_name: jd
target_url: "https://zhaopin.jd.com/web/job/job_info_list/3"
max_pages: 100
headless: true
crawler:
  patterns:
    next_button:
      - "li[title='下一页']"
page_actions:
  - type: "save_html"
    clean_html: true
rate_limit:
  requests_per_minute: 35
  burst_capacity: 3
  min_interval: 1.2
