project_name: tencent
target_url: "https://careers.tencent.com/search.html?query=at_1"
max_pages: 100
headless: true
crawler:
  patterns:
    next_button:
      - "li.next"
interceptors:
  - "disable_trace"
page_actions:
  - type: "eval_js"
    builtin: "link_capture"
    replace:
      listSelectors:
        - ".recruit-list"
      clickSelectors:
        - "a.recruit-list-link"
    use_safe_eval: true
  - type: "save_html"
    clean_html: true
rate_limit:
  requests_per_minute: 35
  burst_capacity: 3
  min_interval: 1.0
