project_name: zhipu
target_url: "https://zhipu-ai.jobs.feishu.cn/index"
max_pages: 100
headless: true
crawler:
  patterns:
    next_button:
      - "li[title='下一页']"
interceptors:
  - "disable_trace"
after_response:
  - type: "save_json"
    url_contains: "/api/v1/search/job/posts"
rate_limit:
  requests_per_minute: 35
  burst_capacity: 3
  min_interval: 1.2
